public class HR_DataformFieldPreventerTest{

private String Name;
private String attending_min_hrs_of_Overal;
private String attending_min_hrs_Capital_Markets;
private String attending_min_hrs_CL;
private String attending_min_hrs_E_business;
private String attending_min_hrs_E_media;
private String attending_min_hrs_Facilities;
private String attending_min_hrs_Finance;
private String attending_min_hrs_Inside_Sales;
private String attending_min_hrs_IS;
private String attending_min_hrs_Marketing;
private String attending_min_hrs_Operations;
private String attending_min_hrs_Sales_DIT;
private String attending_min_hrs_Sales_Mani;




public String getName() {
return Name;
}
public void setName(String firstName) {
this.Name= firstName;
}

public String getattending_min_hrs_of_Overal() {
return attending_min_hrs_of_Overal;
}
public void setattending_min_hrs_of_Overal(String add) {
this.attending_min_hrs_of_Overal=add;
}
public String getattending_min_hrs_Capital_Markets() {
return attending_min_hrs_Capital_Markets;
}
public void setattending_min_hrs_Capital_Markets(String email) {
this.attending_min_hrs_Capital_Markets= email;
}
public String getattending_min_hrs_CL() {
return attending_min_hrs_CL;
}
public void setattending_min_hrs_CL(String add) {
this.attending_min_hrs_CL=add;
}
public String getattending_min_hrs_E_business() {
return attending_min_hrs_E_business;
}
public void setattending_min_hrs_E_business(String add) {
this.attending_min_hrs_E_business=add;
}
public String getattending_min_hrs_E_media() {
return attending_min_hrs_E_media;
}
public void setattending_min_hrs_E_media(String add) {
this.attending_min_hrs_E_media=add;
}


public String getattending_min_hrs_Facilities() {
return attending_min_hrs_Facilities;
}
public void setattending_min_hrs_Facilities(String add) {
this.attending_min_hrs_Facilities=add;
}
public String getattending_min_hrs_Finance() {
return attending_min_hrs_Finance;
}
public void setattending_min_hrs_Finance(String add) {
this.attending_min_hrs_Finance=add;
}
public String getattending_min_hrs_Inside_Sales() {
return attending_min_hrs_Inside_Sales;
}
public void setattending_min_hrs_Inside_Sales(String add) {
this.attending_min_hrs_Inside_Sales=add;
}
public String getattending_min_hrs_IS() {
return attending_min_hrs_IS;
}
public void setattending_min_hrs_IS(String add) {
this.attending_min_hrs_IS=add;
}
public String getattending_min_hrs_Marketing() {
return attending_min_hrs_Marketing;
}
public void setattending_min_hrs_Marketing(String add) {
this.attending_min_hrs_Marketing=add;
}
public String getattending_min_hrs_Operations() {
return attending_min_hrs_Operations;
}
public void setattending_min_hrs_Operations(String add) {
this.attending_min_hrs_Operations=add;
}
public String getattending_min_hrs_Sales_DIT() {
return attending_min_hrs_Sales_DIT;
}
public void setattending_min_hrs_Sales_DIT(String add) {
this.attending_min_hrs_Sales_DIT=add;
}
public String getattending_min_hrs_Sales_Mani() {
return attending_min_hrs_Sales_Mani;
}
public void setattending_min_hrs_Sales_Mani(String add) {
this.attending_min_hrs_Sales_Mani=add;
}


static testMethod void myTest() {


HR_DataformFieldPreventerTest controller = new HR_DataformFieldPreventerTest();
controller.getName();
controller.setName('abc');
controller.getattending_min_hrs_of_Overal();
controller.setattending_min_hrs_of_Overal('def');
controller.getattending_min_hrs_Capital_Markets();
controller.setattending_min_hrs_Capital_Markets('def');
controller.getattending_min_hrs_CL();
controller.setattending_min_hrs_CL('def');
controller.getattending_min_hrs_E_business();
controller.setattending_min_hrs_E_business('def');
controller.getattending_min_hrs_E_media();
controller.setattending_min_hrs_E_media('def');

controller.getattending_min_hrs_Facilities();
controller.setattending_min_hrs_Facilities('def');


controller.getattending_min_hrs_Finance();
controller.setattending_min_hrs_Finance('def');

controller.getattending_min_hrs_Inside_Sales();
controller.setattending_min_hrs_Inside_Sales('def');
controller.getattending_min_hrs_IS();
controller.setattending_min_hrs_IS('def');
controller.getattending_min_hrs_Marketing();
controller.setattending_min_hrs_Marketing('def');
controller.getattending_min_hrs_Operations();
controller.setattending_min_hrs_Operations('def');


controller.getattending_min_hrs_Sales_DIT();
controller.setattending_min_hrs_Sales_DIT('def');
controller.getattending_min_hrs_Sales_Mani();
controller.setattending_min_hrs_Sales_Mani('def');


}






}