public class SalesDataController {
ApexPages.StandardController controller{get; set;}
private String Name;
private String Month;
private String Year;
private String Achieve_intended_positioning_for_CLP_Gr;
private String Achieve_intended_positioning_for_CMP_Gr;
private String Achieve_intended_positioning_for_EbizP;
private String Achieve_intended_positioning_for_EmedP;

private String Achieve_intended_positioning_for_SOPSP;
private String Achieve_sales_process_compliance_EbizP;
private String Achieve_sales_process_compliance_EmedP;
private String Achieve_sales_process_compliance_for_CLP;
private String Achieve_sales_process_compliance_for_CMP;

private String Achieve_sales_process_compliance_SO;
private String Bookings_for_the_organization;
private String CSAT_score_for_Operations;
private String CSAT_score_for_the_organization;
private String Customer_perception_of_Tavant;
private String Existing_client_salesbillings_in_Capita;
private String Existing_client_sales_billings_in_CLP;
private String Existing_client_sales_billings_in_EbizP;
private String Existing_client_sales_billings_in_EmedP;
private String Existing_client_sales_billings_in_SOPSP;



private String New_clients_in_CMP;
private String New_customers_in_CMP;
private String New_sales_billings_in_CLP;
private String New_sales_billings_in_CMP;
private String New_sales_billings_in_EbizP;
private String New_sales_billings_in_EmedP;
private String New_sales_billings_in_SOPSP;
private String number_of_client_visits_by_GDMs_SPMs;
private String Number_of_new_clients_in_CLP;
private String Number_of_new_clients_in_EbizP;
private String Number_of_new_clients_in_EmedP;
private String Number_of_new_clients_in_SOPSP;
private String Number_of_new_customers_in_CLP;
private String Number_of_new_customers_in_EbizP;
private String Number_of_new_customers_in_EmedP;
private String Number_of_new_customers_in_SOPSP;
private String Number_of_qualified_leads_for_CLP;
private String Number_of_qualified_leads_for_CMP;
private String Number_of_qualified_leads_for_EbizP;
private String Number_of_qualified_leads_for_EmedP;
private String Number_of_qualified_leads_for_SOPSP;
private String numbof_whitepapers_case_studies_marketin;
private String Revenue_from_Billings_for_the_org;
private String Sales_effectiveness_for_the_organization;
private String Total_bookings_in_CLP;
private String Total_bookings_in_CMP;
private String Total_IT_budget_of_all_clients_in_CL;
private String Total_IT_budget_of_all_clients_in_CMP;
private String Total_IT_budget_of_all_clients_in_e_biz;
private String Total_IT_budget_of_all_clients_in_e_med;
private String Total_IT_budget_of_all_clients_in_SOPS;
private String Total_revenue_from_new_CLS;
private String Total_revenue_from_new_CMS;
private String Total_revenue_from_new_e_biz_services;
private String Total_revenue_from_new_e_media_services;
private String Total_revenue_from_new_SOPS_services;


public String getAchieve_sales_process_compliance_SO() {
return Achieve_sales_process_compliance_SO;
}
public void setAchieve_sales_process_compliance_SO(String add) {
this.Achieve_sales_process_compliance_SO=add;
}
public String getBookings_for_the_organization() {
return Bookings_for_the_organization;
}
public void setBookings_for_the_organization(String add) {
this.Bookings_for_the_organization=add;
}
public String getCSAT_score_for_Operations() {
return CSAT_score_for_Operations;
}
public void setCSAT_score_for_Operations(String add) {
this.CSAT_score_for_Operations=add;
}

public String getCSAT_score_for_the_organization() {
return CSAT_score_for_the_organization;
}
public void setCSAT_score_for_the_organization(String add) {
this.CSAT_score_for_the_organization=add;
}

public String getCustomer_perception_of_Tavant() {
return Customer_perception_of_Tavant;
}
public void setCustomer_perception_of_Tavant(String add) {
this.Customer_perception_of_Tavant=add;
}



public String getExisting_client_salesbillings_in_Capita() {
return Existing_client_salesbillings_in_Capita;
}
public void setExisting_client_salesbillings_in_Capita(String add) {
this.Existing_client_salesbillings_in_Capita=add;
}
public String getExisting_client_sales_billings_in_CLP() {
return Existing_client_sales_billings_in_CLP;
}
public void setExisting_client_sales_billings_in_CLP(String add) {
this.Existing_client_sales_billings_in_CLP=add;
}
public String getExisting_client_sales_billings_in_EbizP() {
return Existing_client_sales_billings_in_EbizP;
}
public void setExisting_client_sales_billings_in_EbizP(String add) {
this.Existing_client_sales_billings_in_EbizP=add;
}

public String getExisting_client_sales_billings_in_EmedP() {
return Existing_client_sales_billings_in_EmedP;
}
public void setExisting_client_sales_billings_in_EmedP(String add) {
this.Existing_client_sales_billings_in_EmedP=add;
}

public String getExisting_client_sales_billings_in_SOPSP() {
return Existing_client_sales_billings_in_SOPSP;
}
public void setExisting_client_sales_billings_in_SOPSP(String add) {
this.Existing_client_sales_billings_in_SOPSP=add;
}





public String getAchieve_intended_positioning_for_SOPSP() {
return Achieve_intended_positioning_for_SOPSP;
}
public void setAchieve_intended_positioning_for_SOPSP(String add) {
this.Achieve_intended_positioning_for_SOPSP=add;
}
public String getAchieve_sales_process_compliance_EbizP() {
return Achieve_sales_process_compliance_EbizP;
}
public void setAchieve_sales_process_compliance_EbizP(String add) {
this.Achieve_sales_process_compliance_EbizP=add;
}
public String getAchieve_sales_process_compliance_EmedP() {
return Achieve_sales_process_compliance_EmedP;
}
public void setAchieve_sales_process_compliance_EmedP(String add) {
this.Achieve_sales_process_compliance_EmedP=add;
}
public String getAchieve_sales_process_compliance_for_CLP() {
return Achieve_sales_process_compliance_for_CLP;
}
public void setAchieve_sales_process_compliance_for_CLP(String add) {
this.Achieve_sales_process_compliance_for_CLP=add;
}

public String getAchieve_intended_positioning_for_CLP_Gr() {
return Achieve_intended_positioning_for_CLP_Gr;
}
public void setAchieve_intended_positioning_for_CLP_Gr(String add) {
this.Achieve_intended_positioning_for_CLP_Gr=add;
}

public String getAchieve_intended_positioning_for_CMP_Gr() {
return Achieve_intended_positioning_for_CMP_Gr;
}
public void setAchieve_intended_positioning_for_CMP_Gr(String add) {
this.Achieve_intended_positioning_for_CMP_Gr=add;
}
public String getAchieve_intended_positioning_for_EbizP() {
return Achieve_intended_positioning_for_EbizP;
}
public void setAchieve_intended_positioning_for_EbizP(String add) {
this.Achieve_intended_positioning_for_EbizP=add;
}

public String getAchieve_intended_positioning_for_EmedP() {
return Achieve_intended_positioning_for_EmedP;
}
public void setAchieve_intended_positioning_for_EmedP(String add) {
this.Achieve_intended_positioning_for_EmedP=add;
}

public String getAchieve_sales_process_compliance_for_CMP() {
return Achieve_sales_process_compliance_for_CMP;
}
public void setAchieve_sales_process_compliance_for_CMP(String add) {
this.Achieve_sales_process_compliance_for_CMP=add;
}
public String getName() {
return Name;
}
public void setName(String firstName) {
this.Name= firstName;
}

public String getMonth() {
return Month;
}
public void setMonth(String add) {
this.Month=add;
}
public String getYear() {
return Year;
}
public void setYear(String add) {
this.Year=add;
}




public String getTotal_IT_budget_of_all_clients_in_e_med() {
return Total_IT_budget_of_all_clients_in_e_med;
}
public void setTotal_IT_budget_of_all_clients_in_e_med(String add) {
this.Total_IT_budget_of_all_clients_in_e_med=add;
}

public String getTotal_IT_budget_of_all_clients_in_SOPS() {
return Total_IT_budget_of_all_clients_in_SOPS;
}
public void setTotal_IT_budget_of_all_clients_in_SOPS(String add) {
this.Total_IT_budget_of_all_clients_in_SOPS=add;
}

public String getTotal_revenue_from_new_CLS() {
return Total_revenue_from_new_CLS;
}
public void setTotal_revenue_from_new_CLS(String add) {
this.Total_revenue_from_new_CLS=add;
}


public String getTotal_revenue_from_new_CMS() {
return Total_revenue_from_new_CMS;
}
public void setTotal_revenue_from_new_CMS(String add) {
this.Total_revenue_from_new_CMS=add;
}

public String getTotal_revenue_from_new_e_biz_services() {
return Total_revenue_from_new_e_biz_services;
}
public void setTotal_revenue_from_new_e_biz_services(String add) {
this.Total_revenue_from_new_e_biz_services=add;
}

public String getTotal_revenue_from_new_e_media_services() {
return Total_revenue_from_new_e_media_services;
}
public void setTotal_revenue_from_new_e_media_services(String add) {
this.Total_revenue_from_new_e_media_services=add;
}

public String getTotal_revenue_from_new_SOPS_services() {
return Total_revenue_from_new_SOPS_services;
}
public void setTotal_revenue_from_new_SOPS_services(String add) {
this.Total_revenue_from_new_SOPS_services=add;
}
public String getTotal_bookings_in_CLP() {
return Total_bookings_in_CLP;
}
public void setTotal_bookings_in_CLP(String add) {
this.Total_bookings_in_CLP=add;
}


public String getTotal_bookings_in_CMP() {
return Total_bookings_in_CMP;
}
public void setTotal_bookings_in_CMP(String add) {
this.Total_bookings_in_CMP=add;
}


public String getTotal_IT_budget_of_all_clients_in_CL() {
return Total_IT_budget_of_all_clients_in_CL;
}
public void setTotal_IT_budget_of_all_clients_in_CL(String add) {
this.Total_IT_budget_of_all_clients_in_CL=add;
}


public String getTotal_IT_budget_of_all_clients_in_CMP() {
return Total_IT_budget_of_all_clients_in_CMP;
}
public void setTotal_IT_budget_of_all_clients_in_CMP(String add) {
this.Total_IT_budget_of_all_clients_in_CMP=add;
}


public String getTotal_IT_budget_of_all_clients_in_e_biz() {
return Total_IT_budget_of_all_clients_in_e_biz;
}
public void setTotal_IT_budget_of_all_clients_in_e_biz(String add) {
this.Total_IT_budget_of_all_clients_in_e_biz=add;
}
public String getSales_effectiveness_for_the_organization() {
return Sales_effectiveness_for_the_organization;
}
public void setSales_effectiveness_for_the_organization(String add) {
this.Sales_effectiveness_for_the_organization=add;
}



public String getNew_clients_in_CMP() {
return New_clients_in_CMP;
}
public void setNew_clients_in_CMP(String add) {
this.New_clients_in_CMP=add;
}


public String getNew_customers_in_CMP() {
return New_customers_in_CMP;
}
public void setNew_customers_in_CMP(String add) {
this.New_customers_in_CMP=add;
}


public String getNew_sales_billings_in_CLP() {
return New_sales_billings_in_CLP;
}
public void setNew_sales_billings_in_CLP(String add) {
this.New_sales_billings_in_CLP=add;
}


public String getNew_sales_billings_in_CMP() {
return New_sales_billings_in_CMP;
}
public void setNew_sales_billings_in_CMP(String add) {
this.New_sales_billings_in_CMP=add;
}


public String getNew_sales_billings_in_EbizP() {
return New_sales_billings_in_EbizP;
}
public void setNew_sales_billings_in_EbizP(String add) {
this.New_sales_billings_in_EbizP=add;
}

public String getNew_sales_billings_in_EmedP() {
return New_sales_billings_in_EmedP;
}
public void setNew_sales_billings_in_EmedP(String add) {
this.New_sales_billings_in_EmedP=add;
}


public String getNew_sales_billings_in_SOPSP() {
return New_sales_billings_in_SOPSP;
}
public void setNew_sales_billings_in_SOPSP(String add) {
this.New_sales_billings_in_SOPSP=add;
}

public String getnumber_of_client_visits_by_GDMs_SPMs() {
return number_of_client_visits_by_GDMs_SPMs;
}
public void setnumber_of_client_visits_by_GDMs_SPMs(String add) {
this.number_of_client_visits_by_GDMs_SPMs=add;
}


public String getNumber_of_new_clients_in_CLP() {
return Number_of_new_clients_in_CLP;
}
public void setNumber_of_new_clients_in_CLP(String add) {
this.Number_of_new_clients_in_CLP=add;
}


public String getNumber_of_new_clients_in_EbizP() {
return Number_of_new_clients_in_EbizP;
}
public void setNumber_of_new_clients_in_EbizP(String add) {
this.Number_of_new_clients_in_EbizP=add;
}

public String getNumber_of_new_clients_in_EmedP() {
return Number_of_new_clients_in_EmedP;
}
public void setNumber_of_new_clients_in_EmedP(String add) {
this.Number_of_new_clients_in_EmedP=add;
}


public String getNumber_of_new_clients_in_SOPSP() {
return Number_of_new_clients_in_SOPSP;
}
public void setNumber_of_new_clients_in_SOPSP(String add) {
this.Number_of_new_clients_in_SOPSP=add;
}


public String getNumber_of_new_customers_in_CLP() {
return Number_of_new_customers_in_CLP;
}
public void setNumber_of_new_customers_in_CLP(String add) {
this.Number_of_new_customers_in_CLP=add;
}


public String getNumber_of_new_customers_in_EbizP() {
return Number_of_new_customers_in_EbizP;
}
public void setNumber_of_new_customers_in_EbizP(String add) {
this.Number_of_new_customers_in_EbizP=add;
}


public String getNumber_of_new_customers_in_EmedP() {
return Number_of_new_customers_in_EmedP;
}
public void setNumber_of_new_customers_in_EmedP(String add) {
this.Number_of_new_customers_in_EmedP=add;
}

public String getNumber_of_new_customers_in_SOPSP() {
return Number_of_new_customers_in_SOPSP;
}
public void setNumber_of_new_customers_in_SOPSP(String add) {
this.Number_of_new_customers_in_SOPSP=add;
}


public String getNumber_of_qualified_leads_for_CLP() {
return Number_of_qualified_leads_for_CLP;
}
public void setNumber_of_qualified_leads_for_CLP(String add) {
this.Number_of_qualified_leads_for_CLP=add;
}

public String getNumber_of_qualified_leads_for_CMP() {
return Number_of_qualified_leads_for_CMP;
}
public void setNumber_of_qualified_leads_for_CMP(String add) {
this.Number_of_qualified_leads_for_CMP=add;
}

public String getNumber_of_qualified_leads_for_EbizP() {
return Number_of_qualified_leads_for_EbizP;
}
public void setNumber_of_qualified_leads_for_EbizP(String add) {
this.Number_of_qualified_leads_for_EbizP=add;
}

public String getNumber_of_qualified_leads_for_EmedP() {
return Number_of_qualified_leads_for_EmedP;
}
public void setNumber_of_qualified_leads_for_EmedP(String add) {
this.Number_of_qualified_leads_for_EmedP=add;
}


public String getNumber_of_qualified_leads_for_SOPSP() {
return Number_of_qualified_leads_for_SOPSP;
}
public void setNumber_of_qualified_leads_for_SOPSP(String add) {
this.Number_of_qualified_leads_for_SOPSP=add;
}


public String getnumbof_whitepapers_case_studies_marketin() {
return numbof_whitepapers_case_studies_marketin;
}
public void setnumbof_whitepapers_case_studies_marketin(String add) {
this.numbof_whitepapers_case_studies_marketin=add;
}


public String getRevenue_from_Billings_for_the_org() {
return Revenue_from_Billings_for_the_org;
}
public void setRevenue_from_Billings_for_the_org(String add) {
this.Revenue_from_Billings_for_the_org=add;
}















static testMethod void myTest() {


SalesDataController controller = new SalesDataController();
controller.getName();
controller.setName('abc');
controller.getMonth();
controller.setMonth('abc');
controller.getYear();
controller.setYear('abc');
controller.getAchieve_intended_positioning_for_CLP_Gr();
controller.setAchieve_intended_positioning_for_CLP_Gr('abc');
controller.getAchieve_intended_positioning_for_CMP_Gr();
controller.setAchieve_intended_positioning_for_CMP_Gr('abc');
controller.getAchieve_intended_positioning_for_EbizP();
controller.setYear('abc');
controller.getAchieve_intended_positioning_for_EmedP();
controller.setAchieve_intended_positioning_for_EmedP('abc');
controller.getAchieve_intended_positioning_for_SOPSP();
controller.setAchieve_intended_positioning_for_SOPSP('abc');
controller.getAchieve_sales_process_compliance_EbizP();
controller.setAchieve_sales_process_compliance_EbizP('abc');
controller.getAchieve_sales_process_compliance_EmedP();
controller.setAchieve_sales_process_compliance_EmedP('abc');
controller.getAchieve_sales_process_compliance_for_CLP();
controller.setAchieve_sales_process_compliance_for_CLP('abc');
controller.getAchieve_sales_process_compliance_for_CMP();
controller.setAchieve_sales_process_compliance_for_CMP('abc');
controller.getAchieve_sales_process_compliance_SO();
controller.setAchieve_sales_process_compliance_SO('abc');
controller.getBookings_for_the_organization();
controller.setBookings_for_the_organization('abc');
controller.getCSAT_score_for_Operations();
controller.setCSAT_score_for_Operations('abc');
controller.getCSAT_score_for_the_organization();
controller.setCSAT_score_for_the_organization('abc');
controller.getCustomer_perception_of_Tavant();
controller.setCustomer_perception_of_Tavant('abc');
controller.getExisting_client_salesbillings_in_Capita();
controller.setExisting_client_salesbillings_in_Capita('abc');
controller.getExisting_client_sales_billings_in_CLP();
controller.setExisting_client_sales_billings_in_CLP('abc');
controller.getExisting_client_sales_billings_in_EbizP();
controller.setExisting_client_sales_billings_in_EbizP('abc');
controller.getExisting_client_sales_billings_in_EmedP();
controller.setExisting_client_sales_billings_in_EmedP('abc');
controller.getExisting_client_sales_billings_in_SOPSP();
controller.setExisting_client_sales_billings_in_SOPSP('abc');
controller.getNew_clients_in_CMP();
controller.setNew_clients_in_CMP('abc');
controller.getNew_customers_in_CMP();
controller.setNew_customers_in_CMP('abc');
controller.getNew_sales_billings_in_CLP();
controller.setNew_sales_billings_in_CLP('abc');
controller.getNew_sales_billings_in_CMP();
controller.setNew_sales_billings_in_CMP('abc');
controller.getNew_sales_billings_in_EbizP();
controller.setNew_sales_billings_in_EbizP('abc');
controller.getNew_sales_billings_in_EmedP();
controller.setNew_sales_billings_in_EmedP('abc');
controller.getNew_sales_billings_in_SOPSP();
controller.setNew_sales_billings_in_SOPSP('abc');
controller.getnumber_of_client_visits_by_GDMs_SPMs();
controller.setnumber_of_client_visits_by_GDMs_SPMs('abc');
controller.getNumber_of_new_clients_in_CLP();
controller.setNumber_of_new_clients_in_CLP('abc');
controller.getNumber_of_new_clients_in_EbizP();
controller.setNumber_of_new_clients_in_EbizP('abc');
controller.getNumber_of_new_clients_in_EmedP();
controller.setNumber_of_new_clients_in_EmedP('abc');
controller.getNumber_of_new_clients_in_SOPSP();
controller.setNumber_of_new_clients_in_SOPSP('abc');
controller.getNumber_of_new_customers_in_CLP();
controller.setNumber_of_new_customers_in_CLP('abc');
controller.getNumber_of_new_customers_in_EbizP();
controller.setNumber_of_new_customers_in_EbizP('abc');
controller.getNumber_of_new_customers_in_EmedP();
controller.setNumber_of_new_customers_in_EmedP('abc');
controller.getNumber_of_new_customers_in_SOPSP();
controller.setNumber_of_new_customers_in_SOPSP('abc');
controller.getNumber_of_qualified_leads_for_CLP();
controller.setNumber_of_qualified_leads_for_CLP('abc');
controller.getNumber_of_qualified_leads_for_CMP();
controller.setNumber_of_qualified_leads_for_CMP('abc');
controller.getNumber_of_qualified_leads_for_EbizP();
controller.setNumber_of_qualified_leads_for_EbizP('abc');
controller.getNumber_of_qualified_leads_for_EmedP();
controller.setNumber_of_qualified_leads_for_EmedP('abc');
controller.getNumber_of_qualified_leads_for_SOPSP();
controller.setNumber_of_qualified_leads_for_SOPSP('abc');
controller.getnumbof_whitepapers_case_studies_marketin();
controller.setnumbof_whitepapers_case_studies_marketin('abc');
controller.getRevenue_from_Billings_for_the_org();
controller.setRevenue_from_Billings_for_the_org('abc');
controller.getSales_effectiveness_for_the_organization();
controller.setSales_effectiveness_for_the_organization('abc');
controller.getTotal_bookings_in_CLP();
controller.setTotal_bookings_in_CLP('abc');
controller.getTotal_bookings_in_CMP();
controller.setTotal_bookings_in_CMP('abc');
controller.getTotal_IT_budget_of_all_clients_in_CL();
controller.setTotal_IT_budget_of_all_clients_in_CL('abc');
controller.getTotal_IT_budget_of_all_clients_in_CMP();
controller.setTotal_IT_budget_of_all_clients_in_CMP('abc');
controller.getTotal_IT_budget_of_all_clients_in_e_biz();
controller.setTotal_IT_budget_of_all_clients_in_e_biz('abc');
controller.getTotal_IT_budget_of_all_clients_in_e_med();
controller.setTotal_IT_budget_of_all_clients_in_e_med('abc');
controller.getTotal_IT_budget_of_all_clients_in_SOPS();
controller.setTotal_IT_budget_of_all_clients_in_SOPS('abc');
controller.getTotal_revenue_from_new_CLS();
controller.setTotal_revenue_from_new_CLS('abc');
controller.getTotal_revenue_from_new_CMS();
controller.setTotal_revenue_from_new_CMS('abc');
controller.getTotal_revenue_from_new_e_biz_services();
controller.setTotal_revenue_from_new_e_biz_services('abc');
controller.getTotal_revenue_from_new_e_media_services();
controller.setTotal_revenue_from_new_e_media_services('abc');
controller.getTotal_revenue_from_new_SOPS_services();
controller.setTotal_revenue_from_new_SOPS_services('abc');
}
}