public class Scorecard_InstancesFieldPreventerTest{


 @IsTest(SeeAllData=true) static void myTest() {
    
    ScorecardInstanceController controller = new ScorecardInstanceController();
    Scorecard_InstancesFieldPreventerTest controller1 = new Scorecard_InstancesFieldPreventerTest();
        controller.getscorecarddetails();   
        controller.getscorecardinstancedetails();   
        controller.getfinancemetrics();         
        controller.getcustomermetrics();  
        controller.getlearningmetrics(); 
       
        
              
     
 }




}