public class UpdateScorecard_InstancesNameTest{


 @IsTest(SeeAllData=true) static void myTest() {
    
    ScorecardInstanceController controller = new ScorecardInstanceController();
    UpdateScorecard_InstancesNameTest controller1 = new UpdateScorecard_InstancesNameTest();
        controller.getscorecarddetails();   
        controller.getscorecardinstancedetails();   
        controller.getfinancemetrics();         
        controller.getcustomermetrics();  
        controller.getlearningmetrics(); 
       
        
              
     
 }




}